use_frameworks!

platform :ios, '9.0'

target 'ZXToast_Example' do
  pod 'ZXToast', :path => '../'

  target 'ZXToast_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
